apiVersion: v1
kind: ConfigMap
metadata:
  name: pastebin-config
  namespace: pastebin
data:
  POSTGRES_PORT: "5432"
  REDIS_PORT: "6379"
  RATE_LIMIT_PER_MINUTE: "60"
  RATE_LIMIT_PER_HOUR: "1000"
  PROMETHEUS_ENABLED: "true"
