apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pastebin-ingress
  namespace: pastebin
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  rules:
    - host: pastebin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pastebin-nginx
                port:
                  number: 80
